/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OfficesImport } from './routes/offices'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OfficesRoute = OfficesImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/offices': {
      id: '/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offices': typeof OfficesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offices': typeof OfficesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/offices': typeof OfficesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offices'
  id: '__root__' | '/' | '/offices'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficesRoute: typeof OfficesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficesRoute: OfficesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/offices"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/offices": {
      "filePath": "offices.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
